services:
  api:
    build: ./api
    env_file: ".env"
    network_mode: "host"
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  worker:
    build: ./worker
    env_file: ".env"
    network_mode: "host"
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
